# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secretproxy < Formula
  desc "Local proxy that masks secrets in prompts before they reach the LLM API"
  homepage "https://github.com/secretproxy/secretproxy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_darwin_amd64.tar.gz"
      sha256 "ee70e1410b1b58376543a0aaeac507721477ba38a2ca7d391a7de5c7c42eaa3e"

      define_method(:install) do
        bin.install "secretproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_darwin_arm64.tar.gz"
      sha256 "ad840a00a14475195d927bc51c9efc5f63b2617f6ff024d4bf398ee291ddef5e"

      define_method(:install) do
        bin.install "secretproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_linux_amd64.tar.gz"
      sha256 "d3c2d7f0c713b32989b476638cb918a74aa758017bf8921cfc2c56a4855e8526"
      define_method(:install) do
        bin.install "secretproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_linux_arm64.tar.gz"
      sha256 "410abb02d1d8b0224ebf8d04a5641e3acec3ce42d7578032bfbeb5e849106be4"
      define_method(:install) do
        bin.install "secretproxy"
      end
    end
  end

  test do
    system bin/"secretproxy", "-version"
  end
end
