# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secretproxy < Formula
  desc "Local proxy that masks secrets in prompts before they reach the LLM API"
  homepage "https://github.com/secretproxy/secretproxy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_darwin_amd64.tar.gz"
      sha256 "8eedf28d6edec6ce3d0f270fb474f5540d642e4bde60942c340eb77abc9122ef"

      define_method(:install) do
        bin.install "secretproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_darwin_arm64.tar.gz"
      sha256 "362f851d336fd95cd13c49e539ee4da0c6360ad38a9c73c92a2ea2df6710e9c2"

      define_method(:install) do
        bin.install "secretproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_linux_amd64.tar.gz"
      sha256 "cdba6dcf2fbc1bcc8aa3d541fb7b8683449fabc347de8c8261888ca4a19e11d7"
      define_method(:install) do
        bin.install "secretproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/secretproxy/secretproxy/releases/download/v0.1.0/secretproxy_0.1.0_linux_arm64.tar.gz"
      sha256 "344d388a83dc3f556ea7a31b9e23b00bf826ad5f4068f856ab81277aee5c4684"
      define_method(:install) do
        bin.install "secretproxy"
      end
    end
  end

  test do
    system bin/"secretproxy", "-version"
  end
end
